-- Smart guest list: per-guest record with AI-fillable classification + 3-scenario gift estimates.
-- Replaces the flat invitedGuests/avgGift numbers in wedding_config with a real list.
-- Floor of 400 ILS for any gift estimate (per project convention).

create table
  public.guests (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    config_id bigint not null,

    -- Identity (user input)
    name text not null,
    note text, -- free-form user note fed to the AI classifier ("דוד מצד נדב, רווק")

    -- Classification (filled by AI, editable by user)
    side text, -- 'חתן' | 'כלה' | 'משותף'
    category text, -- one of: family_immediate | family_close | family_extended | friends_bff | friends_close | friends | friends_acquaintance | work_close | work | work_boss | parents_friends | neighbors | abroad
    plus_one boolean not null default false,

    -- Attendance & gift estimation
    attendance_prob numeric(3, 2) not null default 0.85
      check (attendance_prob >= 0 and attendance_prob <= 1),
    gift_low integer not null default 400 check (gift_low >= 400),
    gift_realistic integer not null default 450 check (gift_realistic >= 400),
    gift_high integer not null default 600 check (gift_high >= 400),

    -- AI metadata
    confidence text, -- 'high' | 'medium' | 'low'
    ai_classified_at timestamp with time zone,
    manually_edited boolean not null default false,

    constraint guests_pkey primary key (id),
    constraint guests_config_id_fkey foreign key (config_id) references wedding_config (id) on delete cascade
  ) tablespace pg_default;

create index guests_config_id_idx on public.guests (config_id);

alter table public.guests enable row level security;
create policy "Allow public access to guests" on public.guests for all using (true);

-- Auto-update updated_at on row change
create or replace function public.set_guests_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger guests_updated_at_trigger
  before update on public.guests
  for each row execute function public.set_guests_updated_at();
