-- Creates the wedding configuration parameters (guests, budgets, savings)
create table
  public.wedding_config (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    password_hash text not null, -- Simple shared password to access the wedding
    invited_guests integer not null default 300,
    no_show_percent integer not null default 15,
    avg_gift integer not null default 400,
    monthly_saving integer not null default 3000,
    use_safety_buffer boolean not null default true,
    nadav_mom_gift integer not null default 40000,
    constraint wedding_config_pkey primary key (id)
  ) tablespace pg_default;

-- Creates the expenses table
create table
  public.expenses (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    config_id bigint not null,
    name text not null,
    amount integer not null default 0,
    advance integer not null default 0,
    paid boolean not null default false,
    contact_name text,
    contact_phone text,
    constraint expenses_pkey primary key (id),
    constraint expenses_config_id_fkey foreign key (config_id) references wedding_config (id) on delete cascade
  ) tablespace pg_default;

-- Creates the checklist table
create table
  public.checklist (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    config_id bigint not null,
    text text not null,
    done boolean not null default false,
    category text not null,
    constraint checklist_pkey primary key (id),
    constraint checklist_config_id_fkey foreign key (config_id) references wedding_config (id) on delete cascade
  ) tablespace pg_default;

-- Set up Row Level Security (RLS) to allow all access for now (since we will handle simple password auth client-side for this MVP)
alter table public.wedding_config enable row level security;
alter table public.expenses enable row level security;
alter table public.checklist enable row level security;

create policy "Allow public access to wedding_config" on public.wedding_config for all using (true);
create policy "Allow public access to expenses" on public.expenses for all using (true);
create policy "Allow public access to checklist" on public.checklist for all using (true);
